sonar.projectKey=lengors_scoutdesk-ui
sonar.organization=lengors-github

sonar.projectName=scoutdesk-ui

sonar.sources=src
sonar.tests=test

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.app.json