/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SpecificationsIndexRouteImport } from "./routes/specifications.index";
import { Route as ProfilesIndexRouteImport } from "./routes/profiles.index";
import { Route as SpecificationsNameRouteImport } from "./routes/specifications.$name";
import { Route as ProfilesNameRouteImport } from "./routes/profiles.$name";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SpecificationsIndexRoute = SpecificationsIndexRouteImport.update({
  id: "/specifications/",
  path: "/specifications/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: "/profiles/",
  path: "/profiles/",
  getParentRoute: () => rootRouteImport,
} as any);
const SpecificationsNameRoute = SpecificationsNameRouteImport.update({
  id: "/specifications/$name",
  path: "/specifications/$name",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilesNameRoute = ProfilesNameRouteImport.update({
  id: "/profiles/$name",
  path: "/profiles/$name",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/profiles/$name": typeof ProfilesNameRoute;
  "/specifications/$name": typeof SpecificationsNameRoute;
  "/profiles": typeof ProfilesIndexRoute;
  "/specifications": typeof SpecificationsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/profiles/$name": typeof ProfilesNameRoute;
  "/specifications/$name": typeof SpecificationsNameRoute;
  "/profiles": typeof ProfilesIndexRoute;
  "/specifications": typeof SpecificationsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/profiles/$name": typeof ProfilesNameRoute;
  "/specifications/$name": typeof SpecificationsNameRoute;
  "/profiles/": typeof ProfilesIndexRoute;
  "/specifications/": typeof SpecificationsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/profiles/$name"
    | "/specifications/$name"
    | "/profiles"
    | "/specifications";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/profiles/$name"
    | "/specifications/$name"
    | "/profiles"
    | "/specifications";
  id:
    | "__root__"
    | "/"
    | "/profiles/$name"
    | "/specifications/$name"
    | "/profiles/"
    | "/specifications/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ProfilesNameRoute: typeof ProfilesNameRoute;
  SpecificationsNameRoute: typeof SpecificationsNameRoute;
  ProfilesIndexRoute: typeof ProfilesIndexRoute;
  SpecificationsIndexRoute: typeof SpecificationsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/specifications/": {
      id: "/specifications/";
      path: "/specifications";
      fullPath: "/specifications";
      preLoaderRoute: typeof SpecificationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profiles/": {
      id: "/profiles/";
      path: "/profiles";
      fullPath: "/profiles";
      preLoaderRoute: typeof ProfilesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/specifications/$name": {
      id: "/specifications/$name";
      path: "/specifications/$name";
      fullPath: "/specifications/$name";
      preLoaderRoute: typeof SpecificationsNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profiles/$name": {
      id: "/profiles/$name";
      path: "/profiles/$name";
      fullPath: "/profiles/$name";
      preLoaderRoute: typeof ProfilesNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

declare module "./routes/index" {
  const createFileRoute: CreateFileRoute<
    "/",
    FileRoutesByPath["/"]["parentRoute"],
    FileRoutesByPath["/"]["id"],
    FileRoutesByPath["/"]["path"],
    FileRoutesByPath["/"]["fullPath"]
  >;
}
declare module "./routes/profiles.$name" {
  const createFileRoute: CreateFileRoute<
    "/profiles/$name",
    FileRoutesByPath["/profiles/$name"]["parentRoute"],
    FileRoutesByPath["/profiles/$name"]["id"],
    FileRoutesByPath["/profiles/$name"]["path"],
    FileRoutesByPath["/profiles/$name"]["fullPath"]
  >;
}
declare module "./routes/specifications.$name" {
  const createFileRoute: CreateFileRoute<
    "/specifications/$name",
    FileRoutesByPath["/specifications/$name"]["parentRoute"],
    FileRoutesByPath["/specifications/$name"]["id"],
    FileRoutesByPath["/specifications/$name"]["path"],
    FileRoutesByPath["/specifications/$name"]["fullPath"]
  >;
}
declare module "./routes/profiles.index" {
  const createFileRoute: CreateFileRoute<
    "/profiles/",
    FileRoutesByPath["/profiles/"]["parentRoute"],
    FileRoutesByPath["/profiles/"]["id"],
    FileRoutesByPath["/profiles/"]["path"],
    FileRoutesByPath["/profiles/"]["fullPath"]
  >;
}
declare module "./routes/specifications.index" {
  const createFileRoute: CreateFileRoute<
    "/specifications/",
    FileRoutesByPath["/specifications/"]["parentRoute"],
    FileRoutesByPath["/specifications/"]["id"],
    FileRoutesByPath["/specifications/"]["path"],
    FileRoutesByPath["/specifications/"]["fullPath"]
  >;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesNameRoute: ProfilesNameRoute,
  SpecificationsNameRoute: SpecificationsNameRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  SpecificationsIndexRoute: SpecificationsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
