---
name: Test and make static analysis

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - dev
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - dev

jobs:
  test-and-analysis:
    environment: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run coverage tests
        run: npm run test:coverage
      - name: SonarCloud scane
        if: success() || failure()
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}